namespace: ""

server:
  name: shiny-server
  image: rocker/shiny
  ## only use a major.minor version here.  Not x.y.z or 'latest' because
  ## this is also used to mount the library to the correct location in the container
  tag: 4.4
  user: 997
  group: 997

app:
  repository: ""
  sub-directory: ""

storage:
  library_size: 1Gi

hostname: ""
