apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: shiny-test-1
spec:
  storageClassName: "basic-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r-library-pvc
  namespace: shiny-test-1
spec:
  storageClassName: "basic-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
