apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
   traefik.ingress.kubernetes.io/router.tls.certresolver: sectigo
  name: shiny-server
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: internal-users
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shiny-server
            port: 
              name: http
